/*
 *
 * This file is part of Kopycat emulator software.
 *
 * Copyright (C) 2020 INFORION, LLC
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * Non-free licenses may also be purchased from INFORION, LLC, 
 * for users who do not want their programs protected by the GPL. 
 * Contact us for details kopycat@inforion.ru
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */
package ru.inforion.lab403.kopycat.veos.ports.cstdlib


object CTypeB {

    const val _ISupper = 1 shl 0	/* UPPERCASE.  */
    const val _ISlower = 1 shl 1	/* lowercase.  */
    const val _ISalpha = 1 shl 2	/* Alphabetic.  */
    const val _ISdigit = 1 shl 3	/* Numeric.  */
    const val _ISxdigit= 1 shl 4	/* Hexadecimal numeric.  */
    const val _ISspace = 1 shl 5	/* Whitespace.  */
    const val _ISprint = 1 shl 6	/* Printing.  */
    const val _ISgraph = 1 shl 7	/* Graphical.  */
    const val _ISblank = 1 shl 8	/* Blank (usually SPC and TAB).  */
    const val _IScntrl = 1 shl 9	/* Control character.  */
    const val _ISpunct = 1 shl 10	/* Punctuation.  */
    const val _ISalnum = 1 shl 11

    val data = arrayOf(
                /*    0  ^@   */ _IScntrl,
                /*    1  ^A   */ _IScntrl,
                /*    2  ^B   */ _IScntrl,
                /*    3  ^C   */ _IScntrl,
                /*    4  ^D   */ _IScntrl,
                /*    5  ^E   */ _IScntrl,
                /*    6  ^F   */ _IScntrl,
                /*    7  ^G   */ _IScntrl,
                /*    8  ^H   */ _IScntrl,
                /*    9  ^I   */ _ISspace or _ISblank or _IScntrl,
                /*   10  ^J   */ _ISspace or _IScntrl,
                /*   11  ^K   */ _ISspace or _IScntrl,
                /*   12  ^L   */ _ISspace or _IScntrl,
                /*   13  ^M   */ _ISspace or _IScntrl,
                /*   14  ^N   */ _IScntrl,
                /*   15  ^O   */ _IScntrl,
                /*   16  ^P   */ _IScntrl,
                /*   17  ^Q   */ _IScntrl,
                /*   18  ^R   */ _IScntrl,
                /*   19  ^S   */ _IScntrl,
                /*   20  ^T   */ _IScntrl,
                /*   21  ^U   */ _IScntrl,
                /*   22  ^V   */ _IScntrl,
                /*   23  ^W   */ _IScntrl,
                /*   24  ^X   */ _IScntrl,
                /*   25  ^Y   */ _IScntrl,
                /*   26  ^Z   */ _IScntrl,
                /*   27  ^[   */ _IScntrl,
                /*   28  ^\   */ _IScntrl,
                /*   29  ^]   */ _IScntrl,
                /*   30  ^^   */ _IScntrl,
                /*   31  ^_   */ _IScntrl,
                /*   32       */ _ISspace or _ISprint or _ISblank,
                /*   33  !    */ _ISprint or _ISgraph or _ISpunct,
                /*   34  "    */ _ISprint or _ISgraph or _ISpunct,
                /*   35  #    */ _ISprint or _ISgraph or _ISpunct,
                /*   36  $    */ _ISprint or _ISgraph or _ISpunct,
                /*   37  %    */ _ISprint or _ISgraph or _ISpunct,
                /*   38  &    */ _ISprint or _ISgraph or _ISpunct,
                /*   39  '    */ _ISprint or _ISgraph or _ISpunct,
                /*   40  (    */ _ISprint or _ISgraph or _ISpunct,
                /*   41  )    */ _ISprint or _ISgraph or _ISpunct,
                /*   42  *    */ _ISprint or _ISgraph or _ISpunct,
                /*   43  +    */ _ISprint or _ISgraph or _ISpunct,
                /*   44  ,    */ _ISprint or _ISgraph or _ISpunct,
                /*   45  -    */ _ISprint or _ISgraph or _ISpunct,
                /*   46  .    */ _ISprint or _ISgraph or _ISpunct,
                /*   47  /    */ _ISprint or _ISgraph or _ISpunct,
                /*   48  0    */ _ISdigit or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   49  1    */ _ISdigit or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   50  2    */ _ISdigit or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   51  3    */ _ISdigit or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   52  4    */ _ISdigit or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   53  5    */ _ISdigit or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   54  6    */ _ISdigit or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   55  7    */ _ISdigit or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   56  8    */ _ISdigit or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   57  9    */ _ISdigit or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   58  :    */ _ISprint or _ISgraph or _ISpunct,
                /*   59  ;    */ _ISprint or _ISgraph or _ISpunct,
                /*   60  <    */ _ISprint or _ISgraph or _ISpunct,
                /*   61  =    */ _ISprint or _ISgraph or _ISpunct,
                /*   62  >    */ _ISprint or _ISgraph or _ISpunct,
                /*   63  ?    */ _ISprint or _ISgraph or _ISpunct,
                /*   64  @    */ _ISprint or _ISgraph or _ISpunct,
                /*   65  A    */ _ISupper or _ISalpha or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   66  B    */ _ISupper or _ISalpha or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   67  C    */ _ISupper or _ISalpha or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   68  D    */ _ISupper or _ISalpha or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   69  E    */ _ISupper or _ISalpha or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   70  F    */ _ISupper or _ISalpha or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   71  G    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   72  H    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   73  I    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   74  J    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   75  K    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   76  L    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   77  M    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   78  N    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   79  O    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   80  P    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   81  Q    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   82  R    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   83  S    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   84  T    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   85  U    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   86  V    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   87  W    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   88  X    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   89  Y    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   90  Z    */ _ISupper or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*   91  [    */ _ISprint or _ISgraph or _ISpunct,
                /*   92  \    */ _ISprint or _ISgraph or _ISpunct,
                /*   93  ]    */ _ISprint or _ISgraph or _ISpunct,
                /*   94  ^    */ _ISprint or _ISgraph or _ISpunct,
                /*   95  _    */ _ISprint or _ISgraph or _ISpunct,
                /*   96  `    */ _ISprint or _ISgraph or _ISpunct,
                /*   97  a    */ _ISlower or _ISalpha or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   98  b    */ _ISlower or _ISalpha or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*   99  c    */ _ISlower or _ISalpha or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*  100  d    */ _ISlower or _ISalpha or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*  101  e    */ _ISlower or _ISalpha or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*  102  f    */ _ISlower or _ISalpha or _ISxdigit or _ISprint or _ISgraph or _ISalnum,
                /*  103  g    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  104  h    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  105  i    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  106  j    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  107  k    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  108  l    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  109  m    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  110  n    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  111  o    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  112  p    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  113  q    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  114  r    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  115  s    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  116  t    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  117  u    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  118  v    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  119  w    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  120  x    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  121  y    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  122  z    */ _ISlower or _ISalpha or _ISprint or _ISgraph or _ISalnum,
                /*  123  {    */ _ISprint or _ISgraph or _ISpunct,
                /*  124  |    */ _ISprint or _ISgraph or _ISpunct,
                /*  125  }    */ _ISprint or _ISgraph or _ISpunct,
                /*  126  ~    */ _ISprint or _ISgraph or _ISpunct,
                /*  127  ^?   */ _IScntrl,
                /*  128  M-^@ */ 0,
                /*  129  M-^A */ 0,
                /*  130  M-^B */ 0,
                /*  131  M-^C */ 0,
                /*  132  M-^D */ 0,
                /*  133  M-^E */ 0,
                /*  134  M-^F */ 0,
                /*  135  M-^G */ 0,
                /*  136  M-^H */ 0,
                /*  137  M-^I */ 0,
                /*  138  M-^J */ 0,
                /*  139  M-^K */ 0,
                /*  140  M-^L */ 0,
                /*  141  M-^M */ 0,
                /*  142  M-^N */ 0,
                /*  143  M-^O */ 0,
                /*  144  M-^P */ 0,
                /*  145  M-^Q */ 0,
                /*  146  M-^R */ 0,
                /*  147  M-^S */ 0,
                /*  148  M-^T */ 0,
                /*  149  M-^U */ 0,
                /*  150  M-^V */ 0,
                /*  151  M-^W */ 0,
                /*  152  M-^X */ 0,
                /*  153  M-^Y */ 0,
                /*  154  M-^Z */ 0,
                /*  155  M-^[ */ 0,
                /*  156  M-^\ */ 0,
                /*  157  M-^] */ 0,
                /*  158  M-^^ */ 0,
                /*  159  M-^_ */ 0,
                /*  160  M-   */ 0,
                /*  161  M-!  */ 0,
                /*  162  M-"  */ 0,
                /*  163  M-#  */ 0,
                /*  164  M-$  */ 0,
                /*  165  M-%  */ 0,
                /*  166  M-&  */ 0,
                /*  167  M-'  */ 0,
                /*  168  M-(  */ 0,
                /*  169  M-)  */ 0,
                /*  170  M-*  */ 0,
                /*  171  M-+  */ 0,
                /*  172  M-,  */ 0,
                /*  173  M--  */ 0,
                /*  174  M-.  */ 0,
                /*  175  M-/  */ 0,
                /*  176  M-0  */ 0,
                /*  177  M-1  */ 0,
                /*  178  M-2  */ 0,
                /*  179  M-3  */ 0,
                /*  180  M-4  */ 0,
                /*  181  M-5  */ 0,
                /*  182  M-6  */ 0,
                /*  183  M-7  */ 0,
                /*  184  M-8  */ 0,
                /*  185  M-9  */ 0,
                /*  186  M-:  */ 0,
                /*  187  M-;  */ 0,
                /*  188  M-<  */ 0,
                /*  189  M-=  */ 0,
                /*  190  M->  */ 0,
                /*  191  M-?  */ 0,
                /*  192  M-@  */ 0,
                /*  193  M-A  */ 0,
                /*  194  M-B  */ 0,
                /*  195  M-C  */ 0,
                /*  196  M-D  */ 0,
                /*  197  M-E  */ 0,
                /*  198  M-F  */ 0,
                /*  199  M-G  */ 0,
                /*  200  M-H  */ 0,
                /*  201  M-I  */ 0,
                /*  202  M-J  */ 0,
                /*  203  M-K  */ 0,
                /*  204  M-L  */ 0,
                /*  205  M-M  */ 0,
                /*  206  M-N  */ 0,
                /*  207  M-O  */ 0,
                /*  208  M-P  */ 0,
                /*  209  M-Q  */ 0,
                /*  210  M-R  */ 0,
                /*  211  M-S  */ 0,
                /*  212  M-T  */ 0,
                /*  213  M-U  */ 0,
                /*  214  M-V  */ 0,
                /*  215  M-W  */ 0,
                /*  216  M-X  */ 0,
                /*  217  M-Y  */ 0,
                /*  218  M-Z  */ 0,
                /*  219  M-[  */ 0,
                /*  220  M-\  */ 0,
                /*  221  M-]  */ 0,
                /*  222  M-^  */ 0,
                /*  223  M-_  */ 0,
                /*  224  M-`  */ 0,
                /*  225  M-a  */ 0,
                /*  226  M-b  */ 0,
                /*  227  M-c  */ 0,
                /*  228  M-d  */ 0,
                /*  229  M-e  */ 0,
                /*  230  M-f  */ 0,
                /*  231  M-g  */ 0,
                /*  232  M-h  */ 0,
                /*  233  M-i  */ 0,
                /*  234  M-j  */ 0,
                /*  235  M-k  */ 0,
                /*  236  M-l  */ 0,
                /*  237  M-m  */ 0,
                /*  238  M-n  */ 0,
                /*  239  M-o  */ 0,
                /*  240  M-p  */ 0,
                /*  241  M-q  */ 0,
                /*  242  M-r  */ 0,
                /*  243  M-s  */ 0,
                /*  244  M-t  */ 0,
                /*  245  M-u  */ 0,
                /*  246  M-v  */ 0,
                /*  247  M-w  */ 0,
                /*  248  M-x  */ 0,
                /*  249  M-y  */ 0,
                /*  250  M-z  */ 0,
                /*  251  M-{  */ 0,
                /*  252  M-|  */ 0,
                /*  253  M-}  */ 0,
                /*  254  M-~  */ 0,
                /*  255  M-^? */ 0
        )
}
