package ru.inforion.lab403.gradle.kodegen.utils

import ru.inforion.lab403.gradle.kodegen.Kodegen
import ru.inforion.lab403.gradle.kodegen.tokens.KObject
import ru.inforion.lab403.gradle.kodegen.tokens.KPackage

class ObjectKodegenFactory(val classpath: Classpath) {

    constructor(classpath: Classpath, init: KObject.() -> Unit) : this(classpath) { obj.init() }

    private val kodegen = Kodegen {
        pkg(classpath.pkg) {
            -"This is autogenerated file using Kodegen please do not modify it. Any changes may be lost."
            newlines(1)
            obj(classpath.name) {

            }
        }
    }

    private val pkg = kodegen.children.filterIsInstance<KPackage>().first()
    private val obj = pkg.children.filterIsInstance<KObject>().first()

    fun <T>each(list: List<T>, convert: KObject.(T) -> Unit): ObjectKodegenFactory {
        list.forEach { obj.convert(it) }
        return this
    }

    fun get() = kodegen
}
